### ISSUE TITLE
🔵Área de Projetos (Ambos)

### ISSUE THREAD

**Issue by pauloagsantos** [iptomar/Tech-Art-C#1]
Como utilizador, quero ver uma lista (com um número limitado por página) dos Projetos Concluídos em vez de uma página corrida

Tarefas desta user story:

- [x] #3 
- [x] #26 
- [x] #32 
- [x] #35 
- [x] #36 
- [x] #58 
- [x] #60 
- [x] #61 
- [x] #19
- [x] #26
- [x] #43
- [x] #63

**Comment by brnas02** [comment]
Todas as tarefas associadas a este user story foram concluídas
