### ISSUE TITLE
🟠Adicionar uma caixa para a seleção do ano pretendido

### ISSUE THREAD

**Issue by brnas02** [iptomar/Tech-Art-C#30]
Pretende-se no fim de fazer uma seleção do ano em causa, adicionar uma caixa para que esse ano seja escolhido pelo utilizador

User story:
- [ ] #4

**Comment by JustOverDrive** [comment]
foi criado um dropdown para filtrar por ano de publicação

**Comment by JustOverDrive** [comment]
o dropdown teve as opções organizadas de ano mais recente para mais antigo
